### ISSUE TITLE
Shit's broken, plai.

### ISSUE THREAD

**Issue by NinjaBoyLao** [Plailect/PlaiCDN#11]
It won't even run, i literally just did "download zip", extracted it in downloads, ran an admin command prompt (win10) and tried "python PlaiCDN.py -h" with makerom and the ctr things in the same folder.
![capture](https://cloud.githubusercontent.com/assets/16899151/14480052/2f06806e-00f3-11e6-9e4f-011e183dcd8c.PNG)

**Comment by NinjaBoyLao** [comment]
also, that seemingly working script above is your old script, the very first release, just to make sure python wasn't borked.

**Comment by Plailect** [comment]
You *must* be using python 3, that is an error python 2 will throw.

**Comment by NinjaBoyLao** [comment]
add that into the readme then dammit

**Comment by Plailect** [comment]
"If you are using the script itself instead of the compiled .exe, you will also need Python 3 to be installed, and PyCrypto to be installed."

Can you read?

**Comment by NinjaBoyLao** [comment]
that wasn't there when i last checked

**Comment by Plailect** [comment]
...[5 days ago?](https://github.com/Plailect/PlaiCDN/commit/f1438eb134fadd449462957cdf9a3a055662415d?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8)
