### ISSUE TITLE
Created titles cannot be repaired/redownloaded using the eShop application

### ISSUE THREAD

**Issue by Shinigati** [Plailect/PlaiCDN#15]
So apparently a few people have reported that if you use PlaiCDN to download an update file and then if a new update gets released soon after, it will download to 99% on the 3ds and then say an error occurred. I actually personally downloaded my legit copy of Pokemon X using PlaiCDN, installed it to test this theory and it just so happens that i got the same error when i re-downloaded it on the 3ds as well.

**Comment by llakssz** [comment]
Yes, this is what happens when you use decrypted contents, and give a new junk titlekey.
For cias which are redownloadable and that do not interfere with eshop, you should be using FunkyCIA.
For the situation you mentioned, this tool is a step backwards.

**Comment by Plailect** [comment]
@llakssz: [???????????????](https://gbatemp.net/threads/release-plaicdn-download-and-create-installable-cias-or-3ds-with-just-a-title-id-and-titlekey.422144/page-14#post-6259017)

@Shinigati Redownloading a game you installed this way won't work because Nintendo's servers will see that you haven't actually purchased it, but updates and such will work because those aren't authenticated to ninja via OAUTH2

**Comment by llakssz** [comment]
Plailect... this is not the reason why re/downloading the update from eshop won't work.
It just shows more to me that you don't understand how this whole thing works.
I can send you a cia that is not legit, but you will be able to redownload it from eshop fine, and able update to a new version if released in the future.
Did you ever use FunkyCIA?

**Comment by Plailect** [comment]
Have you tested this?

Do it right now. Get a CIA for a game you don't own, then install it and try to repair the title (which will redownload it if you tell it to after the check).

This will not work unless you have purchased the game.

**Comment by Plailect** [comment]
Additionally, you do not need a valid ticket to download a game update, so it doesn't matter that makerom creates CIAs that have a fake titlekey in the ticket.

**Comment by llakssz** [comment]
Believe what you want to believe. :) I'm not trying to convince you, I'm just trying to stop you convincing everyone else.

**Comment by llakssz** [comment]
@Shinigati - if you want a tool that don't interfere with eshop downloads, please check out FunKeyCIA on gbatemp.

The creator here does not believe it can be done and marked your issue as 'invalid', sorry about that. They must be misinformed.

**Comment by Shinigati** [comment]
Thanks, i already knew about FunkyCIA2 but figured it would be easier to redownload stuff with just the titleid and titlekey but for obvious reasons i don't think i will do that anymore. i can see now that there are problems with this method of downloading as a lot of people keep opposing PlaiCDN for several reasons.

**Comment by Plailect** [comment]
@llakssz

The only thing here I *believe* is that you need to have some facts and evidence before throwing out all these claims. In my experience, updates work, but I'm only testing with titles illegally own so it may be different for pirates.

You could totally be right, but I need more than just insults to understand the issue.

**Comment by llakssz** [comment]
@Shinigati - not FunkyCIA, but FunKeyCIA
http://gbatemp.net/threads/release-funkeycia-make-good-cias-from-eshop-content-no-tickets-needed.423025/
You use a key and title id.

@Plailect 'Could be right'? As I said before, believe what YOU want. Stop making a fool of yourself. If you don't understand, just ask, don't fight. But given how you reacted, you will now have to learn for yourself.
I have nothing to prove to you. I'm just helping people by telling them about a better tool.

**Comment by Plailect** [comment]
Added info on this in the readme

**Comment by Shinigati** [comment]
I strongly agree, regardless of the current state of cia's generated here i think it's rather rude to just point fingers and flame on someone's work instead of trying to work it out with them, for the most part PlaiCDN works fine for games and possibly dlc but as long as you don't install update's there should be no problem, i mean if you wanted to redownload a game from the eshop you should just buy it to begin with.
