### ISSUE TITLE
-deckey doesn't work

### ISSUE THREAD

**Issue by shinji257** [Plailect/PlaiCDN#20]
When attempting to use -deckey it throws a "not defined" error.

Traceback (most recent call last):
  File "./PlaiCDN.py", line 252, in <module>
    print('{:} {:}'.format(codecs.encode(title_id, 'hex'), codecs.encode(decrypted_title_key, 'hex')))
NameError: name 'codecs' is not defined

**Comment by Plailect** [comment]
Fixed
